/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CameraButton")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class CameraButton : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "bf06e141ce286894f829d6476673d097";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Texture m_ButtonIcon = default;
        [SerializeField] public UnityEngine.GameObject m_CameraObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_ButtonIcon),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_CameraObject),
            };
        }
    }
}

#endif
