/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/SmartCam2D")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class SmartCam2D : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "76609c9456e94e64d9938f7f61066415";
        public override string ScriptGUID => s_scriptGUID;

        [Header("Zoom Settings")]
        [SerializeField] public System.Double m_zoom = 10;
        [SerializeField] public System.Double m_zoomMin = 5;
        [SerializeField] public System.Double m_zoomMax = 15;
        [SerializeField] public System.Boolean m_camerFollowPlayer = true;
        [SerializeField] public System.Double m_cameraFollowSpeed = 3;
        [SerializeField] public System.Double m_xOffset = 0;
        [SerializeField] public System.Double m_yOffset = 5;
        [SerializeField] public System.Double m_panSensitivity = 100;
        [SerializeField] public System.Double m_mobileZoomSensitivity = 50;
        [SerializeField] public System.Boolean m_boundary = true;
        [SerializeField] public System.Double m_minBoundaryX = 4;
        [SerializeField] public System.Double m_maxBoundaryX = 10;
        [SerializeField] public System.Double m_minBoundaryY = -10;
        [SerializeField] public System.Double m_maxBoundaryY = 10;
        [SerializeField] public System.Boolean m_deadzone = true;
        [SerializeField] public System.Double m_deadzoneWidth = 3;
        [SerializeField] public System.Double m_deadzoneHeight = 3;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_zoom),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_zoomMin),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_zoomMax),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_camerFollowPlayer),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_cameraFollowSpeed),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_xOffset),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_yOffset),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_panSensitivity),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_mobileZoomSensitivity),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_boundary),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_minBoundaryX),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_maxBoundaryX),
                CreateSerializedProperty(_script.GetPropertyAt(12), m_minBoundaryY),
                CreateSerializedProperty(_script.GetPropertyAt(13), m_maxBoundaryY),
                CreateSerializedProperty(_script.GetPropertyAt(14), m_deadzone),
                CreateSerializedProperty(_script.GetPropertyAt(15), m_deadzoneWidth),
                CreateSerializedProperty(_script.GetPropertyAt(16), m_deadzoneHeight),
            };
        }
    }
}

#endif
